In [8]:
import numpy as np

## Calculate SVD through the eigenvalue problem:

In [9]:
# Create a matrix to calculate SVD of

A = np.array([[3, 1, 1],
              [-1, 3, 1]])
A

array([[ 3,  1,  1],
       [-1,  3,  1]])

In [10]:
# Calculate eigenvalues of the matrix A * A.T

A_1 = np.dot(A, A.T)

e_value_1, e_vector_1 = np.linalg.eigh(A_1)
e_value_1

array([10., 12.])

In [11]:
# Calculate eigenvalues of the matrix A.T * A

A_2 = np.dot(A.T, A)

e_value_2, e_vector_2 = np.linalg.eigh(A_2)
e_value_2 # This should give the same eigenvalues as the previous matrix

array([-2.25970772e-15,  1.00000000e+01,  1.20000000e+01])

In [12]:
# Arrange eigenvalues and corresponding eigenvectors in descending order

idx_1 = e_value_1.argsort()[::-1] # returns the indices of the sorted array in descending order
e_value_1 = e_value_1[idx_1]      # sorts the eigenvalue array in descending order
e_vector_1 = e_vector_1[:, idx_1] # sort the columns of the eigenvector matrix (every column is a separate eigenvector)

idx_2 = e_value_2.argsort()[::-1]
e_value_2 = e_value_2[idx_2]
e_vector_2 = e_vector_2[:, idx_2]

In [14]:
# Define the U, S and V matrices from these eigenvalue matrices and reconstruct A from these.

temp = np.diag(np.sqrt(e_value_1)) # create a diagonal matrix (square) from the eigenvalues
S = np.zeros(A.shape).astype(float) # S is always the same shape as the original matrix
S [:temp.shape[0], :temp.shape[1]] = temp

U = e_vector_1 # U is the matrix of eigenvectors for A * A.T
V = e_vector_2 # V is the matrix of eigenvectors for A.T * A

reconstructed_A = np.dot(U, np.dot(S, V.T)) # A = U * S * V.T
reconstructed_A # The negative sign is just a scaling factor which is inserted due to the eigenvalue problem we solved.

array([[-3., -1., -1.],
       [ 1., -3., -1.]])

In [18]:
A
print(U)
print(S)
print(V)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]
[[-4.08248290e-01  8.94427191e-01 -1.82574186e-01]
 [-8.16496581e-01 -4.47213595e-01 -3.65148372e-01]
 [-4.08248290e-01  2.77555756e-16  9.12870929e-01]]


## Using the numpy library SVD function

In [19]:
U, S, VT = np.linalg.svd(A)
S

array([3.46410162, 3.16227766])

In [20]:
# Reconstruct S again

temp = np.diag(S)
S = np.zeros(A.shape).astype(float)
S [:temp.shape[0], :temp.shape[1]] = temp

reconstructed_A = np.dot(U, np.dot(S, VT))
reconstructed_A

array([[ 3.,  1.,  1.],
       [-1.,  3.,  1.]])

In [21]:
print(U)
print(S)
print(V)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]
[[-4.08248290e-01  8.94427191e-01 -1.82574186e-01]
 [-8.16496581e-01 -4.47213595e-01 -3.65148372e-01]
 [-4.08248290e-01  2.77555756e-16  9.12870929e-01]]


In [66]:
import numpy as np 

In [67]:
A = np.array([[3, 1, 1], [-1, 3, 1]])

In [68]:
A1 = np.dot(A, A.T)
E1, Ev1 = np.linalg.eigh(A1)

In [69]:
print(E1,'\n',Ev1)

[10. 12.] 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [70]:
A2 = np.dot(A.T, A)
E2, Ev2 = np.linalg.eigh(A2)

In [71]:
print(E2,'\n',Ev2)

[-2.25970772e-15  1.00000000e+01  1.20000000e+01] 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01 -8.16496581e-01]
 [ 9.12870929e-01  2.77555756e-16 -4.08248290e-01]]


In [72]:
idx = E1.argsort()[::-1]
E1 = E1[idx]
U = Ev1[:, idx]

idx = E2.argsort()[::-1]
E2 = E2[idx]
V = Ev2[:, idx]

In [78]:
S = np.zeros(A.shape)
S[:E1.size, :E1.size] = np.diag(np.sqrt(E1))

In [79]:
print(U)
print(S)
print(V)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]
[[-4.08248290e-01  8.94427191e-01 -1.82574186e-01]
 [-8.16496581e-01 -4.47213595e-01 -3.65148372e-01]
 [-4.08248290e-01  2.77555756e-16  9.12870929e-01]]


In [82]:
print(np.dot(U, np.dot(S, V.T)))

[[-3. -1. -1.]
 [ 1. -3. -1.]]


In [76]:
A

array([[ 3,  1,  1],
       [-1,  3,  1]])